In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset.csv')

In [4]:
df.head()

,event_id,country_name,iso_code,admin_division,disease_name,disease_subtype,disease_group,causal_agent_type,species_name,is_wild,...,intervention_vector_control_applied,intervention_wildlife_control_applied,intervention_traceability_applied,intervention_treatment_applied,intervention_slaughter_applied,intervention_count,lab_test_performed,diagnostic_method_types,event_status,reason_type
0,1,Argentina,ARG,Buenos Aires,West Nile Fever,NaN,Multiple species,Virus,Equidae,0.0,...,0,0,0,0,0,6,5,Diagnostic test|Clinical,Resolved,First occurrence
1,3,Japan,JPN,Fukuoka,Newcastle disease,NaN,Aves,Virus,Birds,0.0,...,0,0,0,0,0,6,3,Diagnostic test|Clinical,Resolved,Recurrence
2,4,Denmark,DNK,Fyns Amt (2005-2007),Highly pathogenic avian influenza,H5N1,Aves,Virus,Birds,0.0,...,0,0,0,0,0,0,1,Diagnostic test|Clinical,Resolved,First occurrence
3,5,Czech Republic,CZE,Jihomoravský,Highly pathogenic avian influenza,H5N1,Aves,Virus,Wildlife (species unspecified),1.0,...,0,1,0,0,0,8,1,Diagnostic test,Resolved,Recurrence
4,6,Bolivia,BOL,Chuquisaca,Aujeszky's disease,NaN,Multiple species,Virus,Swine,0.0,...,0,1,0,0,0,12,4,Clinical|Diagnostic test,Resolved,Recurrence

In [21]:
print(df.columns.tolist())

['event_id', 'country_name', 'iso_code', 'admin_division', 'disease_name', 'disease_subtype', 'disease_group', 'causal_agent_type', 'species_name', 'is_wild', 'epi_unit_type', 'is_domestic', 'is_aquatic', 'latitude', 'longitude', 'location_approx', 'event_started_on', 'event_confirmed_on', 'event_ended_on', 'outbreak_start_date', 'outbreak_end_date', 'last_occurrence', 'reported_on', 'susceptible', 'cases', 'deaths', 'killed', 'slaughtered', 'vaccinated', 'intervention_quarantine_applied', 'intervention_movement_control_applied', 'intervention_stamping_out_applied', 'intervention_disinfection_applied', 'intervention_surveillance_applied', 'intervention_screening_applied', 'intervention_disposal_applied', 'intervention_vaccination_applied', 'intervention_zoning_applied', 'intervention_vector_control_applied', 'intervention_wildlife_control_applied', 'intervention_traceability_applied', 'intervention_treatment_applied', 'intervention_slaughter_applied', 'intervention_count', 'lab_test_performed', 'diagnostic_method_types', 'event_status', 'reason_type', 'month', 'season']

In [38]:
# Convert date column
df["outbreak_start_date"] = pd.to_datetime(
    df["outbreak_start_date"]
)

# Derive month
df["month"] = df["outbreak_start_date"].dt.month_name()

# Derive season
df["season"] = df["outbreak_start_date"].dt.month.map({
    12: "Winter", 1: "Winter", 2: "Winter",
    3: "Summer", 4: "Summer", 5: "Summer",
    6: "Monsoon", 7: "Monsoon", 8: "Monsoon", 9: "Monsoon",
    10: "Post-Monsoon", 11: "Post-Monsoon"
})

# Select required columns
columns_to_keep = [
    "species_name",
    "is_wild",
    "is_domestic",
    "is_aquatic",
    "causal_agent_type",
    "country_name",
    "latitude",
    "longitude",
    "month",
    "season",
    "susceptible",
    "epi_unit_type",
    "disease_name",
]

data = df[columns_to_keep]

print(data.head())

                     species_name  is_wild  is_domestic  is_aquatic  \
0                         Equidae      0.0            0           0
1                           Birds      0.0            0           0
2                           Birds      0.0            0           0
3  Wildlife (species unspecified)      1.0            0           0
4                           Swine      0.0            0           0

  causal_agent_type    country_name  latitude  longitude     month   season  \
0             Virus       Argentina  -34.4822  -58.51818  February   Winter
1             Virus           Japan   33.3718  130.69360       May   Summer
2             Virus         Denmark   55.3931   10.58160       May   Summer
3             Virus  Czech Republic   48.6962   16.95640       May   Summer
4             Virus         Bolivia  -19.7444  -64.10100    August  Monsoon

   susceptible epi_unit_type                        disease_name
0          640          Farm                    West Nile Fever
1        30477          Farm                  Newcastle disease
2          102          Farm  Highly pathogenic avian influenza
3           54       Village  Highly pathogenic avian influenza
4         1461          Farm                 Aujeszky's disease

In [63]:


pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

summary = pd.DataFrame({
    "Column": data.columns,
    "Unique_Count": [data[col].nunique() for col in data.columns],
    "Unique_Values": [data[col].unique().tolist() for col in data.columns]
})

display(summary)

,Column,Unique_Count,Unique_Values
0,species_name,319,"[Equidae, Birds, Wildlife (species unspecified), Swine, Cattle, Bees, Freshwater drum, Common carp, Sheep, Rainbow trout, Goats, Camelidae, Buffaloes, Rabbits, Wild crustaceans (species unspecified), Tuberculate abalone\n, European flat oyster, Farmed fish (species unspecified), Red swamp crawfish, Sheep/goats (mixed herd), Wild fish (species unspecified), Rabbits/hares (mixed group), Penaeus spp, Pacific whiteleg shrimp, Dogs, Cats, Giant fresh water prawn, Farmed molluscs (species unspecified), Giant tiger prawn or black tiger shrimp, Pacific cupped oyster, Blacklip abalone, Ostreidae (unidentified), Atlantic salmon, Goldfish, Cervidae, Amur carp, American Mink, White clawed crayfish, Blue or edible mussel, Common toad, Australian mud oyster, Mediterranean mussel, North African catfish, Edible frog, Cichlidae (unidentified), Japanese abalone, Brown bullhead, Indian prawn, Impala, Blue shrimp, White clam, Signal crayfish, Whiteleg shrimp, Ibex, Eastern oyster\n, Wild boar, Brown hare (European Hare), Maxima clam, Cuckoo wrasse, Black-headed Gull, Mangrove cupped oyster, Amberjack, Black-lip pearl oyster, Hooded Crow, Rock Pigeon (Rock Dove), Scorpion fish, Blue crayfish, Common frog, Redclaw crayfish, House Crow, American bullfrog, African Elephant, Western roe deer, Common chimpanzee, European bison (wisent), New Zealand green-lipped mussel, Bar-headed Goose, Mallard, Mandarin Duck, American wigeon, Cooper's Hawk, New Zealand scallop, Eurasian Wigeon, Viverridae (unidentified), Red Fox, Chilean flat oyster, Tiger, Mute Swan, Dalmatian pelican, Peregrin falcon, Oriental Magpie-Robin, Plain chachalaca, Saiga Antelope, Atlantic cod, European Rabbit, Barehead goby, Lumpfish, Raccoon dog, Great Egret, Pygmy brocket, ...]"
1,is_wild,2,"[0, 1]"
2,is_domestic,2,"[0, 1]"
3,is_aquatic,2,"[0, 1]"
4,causal_agent_type,6,"[Virus, Parasite, Bacterium, Prion, Fungus, Protozoan]"
5,country_name,194,"[Argentina, Japan, Denmark, Czech Republic, Bolivia, Ecuador, Niger, Israel, Turkey, Botswana, Spain, Costa Rica, Canada, Thailand, United States of America, Belgium, France, United Kingdom, Algeria, Luxembourg, Germany, Azerbaijan, Romania, Bulgaria, Netherlands, Italy, Guinea, Myanmar, Sweden, Portugal, Serbia and Montenegro, Latvia, Afghanistan, Albania, Tunisia, Brazil, Austria, Bosnia and Herzegovina, Cambodia, Cote D'Ivoire, Georgia, Guatemala, Greece, Iran, Hungary, Sudan, Vietnam, Egypt, Mongolia, South Africa, Nicaragua, Kenya, Nigeria, Korea (Rep. of), Jordan, Indonesia, India, China (People's Rep. of), Croatia, Burkina Faso, Iraq, Kazakhstan, Pakistan, Laos, Hong Kong, Slovakia, Malaysia, Poland, Palestinian Territory, Slovenia, Mozambique, Tanzania, Russia, Cameroon, Palestine, Switzerland, Zimbabwe, Ukraine, Kuwait, Djibouti, Korea (Dem People's Rep. of), Norway, Belize, Cyprus, Swaziland, Lesotho, Bangladesh, Lebanon, Peru, New Zealand, Ireland, Mexico, Serbia, Chile, Ghana, Uruguay, Colombia, Saudi Arabia, Zambia, Congo (Rep. of the), ...]"
6,latitude,6038,"[-34.4822, 33.3718, 55.3931, 48.6962, -19.7444, -0.2051, 14.2217, 55.2831, 30.6549, 41.5916, -17.9623661, 54.8689, -3.16277, 42.8619, 10.1278, 51.156, 42.5826, 17.236, 31.718107434, 43.0283, 51.02, 50.79289, 54.76, 43.28595, 33.7581, 40.279652, 49.7798, -19.744, 52.314211, 42.623831, 41.1551, 49.7536, 46.533333, 42.9875, 46.622175, 41.9736, 51.36, 56.0134, 45.8714, 43.7166, 48.7328, 42.52, 47.41, 37.3838, 51.037512, -0.8356, 51.7715, 11.43, 22.4901, 58.3383, 39.1134, 43.97, 57.61, 34.95, 50.094828, 41.26, 34.961454, -25.37496, 44.35, 46.93, 44.34694, 12.0246, 4.63333, 41.62, 15.5, 40.4166, 37.1142, 47.16, 47.2813, 47.3609, 46.4896, 33.8068, 4.89029, 21.3007, 29.8732, 32.5161237246, 46.5699, 49.662103, 35.8762, -33.678, 31.0426, 11.85669, 1.175, 30.351, 41.598101, 6.22783, -22.7719, 36.464561, 31.48, 32.10646, 3.9475, 16.9902, 37.4718, -3.7427, 43.103, 52.24323, 0.6289, 20.93158, 37.9, 32.7559779388, ...]"
7,longitude,6137,"[-58.51818, 130.6936, 10.5816, 16.9564, -64.101, -78.9311, 7.298, 10.2135, 34.9034, 27.4631, 24.67097092, 10.7814, -79.215256, -2.6503, -83.3555, -100.3014, -82.7716, 104.464799, 34.7284073422, -106.7483, 3.85, 2.70767, -6.586, -79.84121, 1.2236, 36.359501, 5.93, 8.067794, 2.950386, 48.8594, 8.7222, 24.8, -89.3417, -0.249847, 27.6556, 5.94, -2.4645, 11.9124, 28.2359, 14.5164, 27.45, 27.32, 14.5041, 13.754364, -77.1493, 6.8565, -9.182, 95.5412, 15.5689, -8.9722, 19.55, 25.68, 71.13, 6.057028, 19.65, 9.8004, -48.9827, 21.11, 15.51, 17.18855, 105.5219, 41.59, -90.25, 22.9, 49.5474, 18.58, 21.0607, 19.3846, 19.3959, 2.9593, 31.64081, 102.9776, 31.2622, 35.150991698, 112.9884, 6.039882, 9.0804, 19.6072, 34.7202, -86.07594, 35.667, 31.2188, 26.746839, 6.80831, 30.96917, 127.200937, 36.08, 36.0317, 34.776, 100.5854, 14.2535, -38.7336, 26.9048, 0.39136, 123.2152, 76.7645, 106.55, 35.2148717848, 18.88585, -2.6, ...]"
8,month,12,"[February, May, August, April, June, March, January, July, October, December, November, September]"
9,season,4,"[Winter, Summer, Monsoon, Post-Monsoon]"
10,susceptible,2410,"[640, 30477, 102, 54, 1461, 585, 28000, 22550, 271400, 6953, 2336, 26780, 23, 1, 646, 1700, 0, 5795, 875, 938, 20801, 4633, 13, 30, 5245, 668, 25, 1320, 116, 62, 5, 168, 126, 34, 5250, 249, 16676, 13396, 83, 4181, 25000, 191, 473971, 8, 49, 5662, 229, 484378, 32400, 18, 9, 1349, 2538, 75, 33, 5308, 2, 150, 3362, 10, 17, 3000, 19, 1061, 2115, 7, 65463, 170, 195597, 417892, 1300, 330, 223, 870, 58, 3, 4000, 891, 1823, 39, 505906, 1346, 2000, 30000, 2100, 50, 41, 467, 54000, 1951, 1093, 130, 4130, 296000, 2199, 98150, 6000, 20074, 24648, 12741, ...]"
11,epi_unit_type,20,"[Farm, Village, Not applicable, Apiary, Lake, Coastal area, River system, Pond, Shell fish bed, Reservoir, Estuary, Backyard, Natural park, Forest, Zoo, Other, Livestock market, Cage, Slaughterhouse, Body of water]"
12,disease_name,193,"[West Nile Fever, Newcastle disease, Highly pathogenic avian influenza, Aujeszky's disease, Foot and mouth disease, Low pathogenic avian influenza, Vesicular stomatitis, Avian infectious laryngotracheitis, Small hive beetle Inf., Viral haemorrhagic septicaemia, Lumpy skin disease, Bluetongue, Equine infectious anaemia, Spring viraemia of carp, American foulbrood of honey bees, Classical swine fever, Anthrax, Contagious equine metritis, Infectious haematopoietic necrosis, Scrapie, Epizootic hemorrhagic disease virus, Sheep pox and goat pox, Rift Valley fever, Peste des petits ruminants, Bovine genital campylobacteriosis, Foot and mouth disease virus, Myxomatosis, Contagious agalactia, African horse sickness, Rabies, Q fever, Avian infectious bronchitis, Porcine reproductive and respiratory syndrome, Varroosis of honey bees, Taura syndrome, Xenohaliotis californiensis, Bonamia ostreae, Maedi-visna, African swine fever, Ovine epididymitis, Aeromonas hydrophila, White spot disease, Brucellosis, Koi herpesvirus disease, Caprine and ovine brucellosis, Fowl typhoid, Epizootic ulcerative syndrome, Swine vesicular disease, Caprine arthritis/encephalitis, Infectious salmon anaemia, Newcastle disease virus, Equine encephalomyelitis, Rabbit haemorrhagic disease, Equine rhinopneumonitis, Equine influenza, Equine viral arteritis, Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis, Enzootic bovine leukosis, Contagious bovine pleuropneumonia, Bovine spongiform encephalopathy, Streptococcus suis, Botulism, Koi herpesvirus, Bonamia exitiosa, Glanders, White tail disease, Bovine babesiosis, Trypanosomosis, Malignant catarrhal fever, Infectious myonecrosis, Infectious hypodermal and haematopoietic necrosis, Equine piroplasmosis, Ostreid herpesvirus-1, Abalone viral mortality, Bovine anaplasmosis, Epizootic haemorrhagic disease, Trichinellosis, Postweaning Multisystemic Wasting Syndrome, Equine encephalosis virus, Influenza A virus, New world screwworm, European foulbrood of honey bees, Venezuelan equine encephalomyelitis, Contagious caprine pleuropneumonia, Crayfish plague, Marteilia refringens, Acarapisosis of honey bees, Batrachochytrium dendrobatidis, Pullorum disease, Mycobacterium tuberculosis, Ranavirus, Leishmaniosis, Dourine, Perkinsus olseni, Hendra viruses, Transmissible gastroenteritis, Bovine tuberculosis, Schmallenberg virus, Enzootic abortion of ewes, Tularemia, ...]"

In [40]:
print(data.columns.tolist())

['species_name', 'is_wild', 'is_domestic', 'is_aquatic', 'causal_agent_type', 'country_name', 'latitude', 'longitude', 'month', 'season', 'susceptible', 'epi_unit_type', 'disease_name']

In [41]:
data.shape

(6363, 13)

In [48]:
display(data.head())

,species_name,is_wild,is_domestic,is_aquatic,causal_agent_type,country_name,latitude,longitude,month,season,susceptible,epi_unit_type,disease_name
0,Equidae,0,0,0,Virus,Argentina,-34.4822,-58.51818,February,Winter,640,Farm,West Nile Fever
1,Birds,0,0,0,Virus,Japan,33.3718,130.69360,May,Summer,30477,Farm,Newcastle disease
2,Birds,0,0,0,Virus,Denmark,55.3931,10.58160,May,Summer,102,Farm,Highly pathogenic avian influenza
3,Wildlife (species unspecified),1,0,0,Virus,Czech Republic,48.6962,16.95640,May,Summer,54,Village,Highly pathogenic avian influenza
4,Swine,0,0,0,Virus,Bolivia,-19.7444,-64.10100,August,Monsoon,1461,Farm,Aujeszky's disease

In [46]:
# Drop rows containing any missing value
data = data.dropna()

# Check resultant row count
print("Remaining rows:", data.shape[0])

Remaining rows: 6332

In [47]:
binary_cols = ["is_wild", "is_domestic", "is_aquatic"]

data[binary_cols] = data[binary_cols].astype(int)

Target distribution

In [52]:
data["disease_name"] = (
    data["disease_name"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.strip()
)

In [53]:
print(data["disease_name"].value_counts())

disease_name
African swine fever virus                                               638
Influenza A viruses of high pathogenicity                               580
Highly pathogenic avian influenza                                       570
High pathogenicity avian influenza viruses                              531
Foot and mouth disease                                                  273
Anthrax                                                                 231
Highly pathogenic influenza A viruses                                   209
Foot and mouth disease virus                                            183
Low pathogenic avian influenza                                          178
Bluetongue virus                                                        153
Newcastle disease                                                       152
West Nile Fever                                                         147
Rabies virus                                                            146
Bluetongue                                                              131
African swine fever                                                     131
Sheep pox and goat pox                                                  121
Newcastle disease virus                                                  92
SARS-CoV-2 in animals                                                    89
Equine infectious anaemia                                                83
Lumpy skin disease virus                                                 69
Classical swine fever                                                    64
Rabies                                                                   60
Rabbit haemorrhagic disease                                              55
Bovine spongiform encephalopathy                                         51
Peste des petits ruminants virus                                         41
Peste des petits ruminants                                               39
Lumpy skin disease                                                       38
Brucellosis                                                              32
Influenza A virus                                                        32
Scrapie                                                                  31
Rift Valley fever                                                        28
Contagious equine metritis                                               26
New world screwworm                                                      26
Koi herpesvirus                                                          24
Rift Valley fever virus                                                  23
Infectious salmon anaemia virus                                          23
Infectious haematopoietic necrosis virus                                 23
Koi herpesvirus disease                                                  23
American foulbrood of honey bees                                         22
Porcine reproductive and respiratory syndrome                            21
European foulbrood of honey bees                                         19
Equine piroplasmosis                                                     18
African horse sickness                                                   18
Viral haemorrhagic septicaemia                                           18
Viral haemorrhagic septicaemia virus                                     17
Vesicular stomatitis                                                     17
Equine influenza virus                                                   17
Small hive beetle Inf.                                                   16
Classical swine fever virus                                              16
Fowl typhoid                                                             16
Equine encephalomyelitis                                                 16
Myxomatosis                                                              15
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis     15
Varroa spp.                                                              14
Leishmaniosis                                                            14
Aujeszky's disease virus                                                 14
Mycoplasma mycoides subsp. mycoides SC                                   14
Contagious bovine pleuropneumonia                                        14
Crayfish plague                                                          13
Epizootic hemorrhagic disease virus                                      13
Equine influenza                                                         13
White spot disease                                                       13
Melissococcus plutonius                                                  12
Venezuelan equine encephalomyelitis                                      12
Avian infectious laryngotracheitis                                       12
Ostreid herpesvirus-1                                                    12
African horse sickness virus                                             11
Caprine arthritis/encephalitis                                           11
Tilapia lake virus disease                                               11
Mycobacterium tuberculosis complex                                       11
Epizootic ulcerative syndrome                                            11
Aethina tumida                                                           11
Aphanomyces invadans                                                     10
Cochliomyia hominivorax                                                  10
Aujeszky's disease                                                       10
Bonamia ostreae                                                          10
Glanders                                                                 10
Perkinsus olseni                                                         10
Gyrodactylus salaris                                                      9
Schmallenberg virus                                                       9
Tularemia                                                                 9
Bonamia exitiosa                                                          9
Acute hepatopancreatic necrosis disease                                   9
Q fever                                                                   9
Spring viraemia of carp                                                   8
Porcine epidemic diarrhoea virus                                          8
Ranavirus                                                                 8
Infectious salmon anaemia                                                 8
Infectious haematopoietic necrosis                                        7
Coxiella burnetii                                                         7
Leishmania spp.                                                           7
Equid herpesvirus-1                                                       7
Haemorrhagic septicaemia                                                  7
Infectious hypodermal and haematopoietic necrosis virus                   7
Middle East respiratory syndrome coronavirus                              7
Equine viral arteritis                                                    7
Porcine reproductive and respiratory syndrome virus                       7
Aphanomyces astaci                                                        7
Burkholderia mallei                                                       7
Brucella melitensis                                                       7
Brucella suis                                                             6
White spot syndrome virus                                                 6
Tilapia lake virus                                                        6
Echinococcus granulosus                                                   6
Theileria equi and Babesia caballi                                        6
Crimean Congo haemorrhagic fever                                          6
Bovine tuberculosis                                                       6
Bovine babesiosis                                                         6
Maedi-visna                                                               6
Varroosis of honey bees                                                   6
Avian infectious bronchitis                                               6
Enzootic bovine leukosis                                                  5
Dourine                                                                   5
Equine arteritis virus                                                    5
Pathogenic rabbit lagoviruses                                             5
Paenibacillus larvae                                                      5
Contagious caprine pleuropneumonia                                        5
Marteilia refringens                                                      5
Brucella abortus                                                          5
Ostreid herpesvirus-1 microvariant                                        5
Trypanosoma evansi                                                        4
Old world screwworm                                                       4
Infectious bursal disease                                                 4
Heartwater                                                                4
Theileria annulata, Theileria orientalis and Theileria parva              4
Bovine anaplasmosis                                                       4
Epizootic haemorrhagic disease                                            4
Batrachochytrium salamandrivorans                                         4
Batrachochytrium dendrobatidis                                            4
Camelpox                                                                  4
Bovine pestiviruses                                                       4
Megalocytivirus pagrus 1                                                  4
Pullorum disease                                                          4
Transmissible gastroenteritis                                             3
Spring viraemia of carp virus                                             3
Contagious agalactia                                                      3
Avian chlamydiosis                                                        3
Mycoplasma gallisepticum                                                  3
Avian mycoplasmosis                                                       3
Infectious myonecrosis virus                                              3
Trichinella spp.                                                          3
Paratuberculosis                                                          3
Surra                                                                     3
Perkinsus marinus                                                         3
Enzootic abortion of ewes                                                 3
Taylorella equigenitalis                                                  2
Japanese encephalitis                                                     2
Xenohaliotis californiensis                                               2
Ovine epididymitis                                                        2
Hepatobacter penaei                                                       2
Equine rhinopneumonitis                                                   2
Red sea bream iridovirus                                                  2
Red sea bream iridoviral disease                                          2
Trypanosomosis                                                            2
White tail disease                                                        2
Infectious hypodermal and haematopoietic necrosis                         2
Infectious myonecrosis                                                    2
Bovine viral diarrhoea                                                    1
Trypanosoma Brucei, T. Congolense, T. Simiae and T. Vivax                 1
Mycobacterium tuberculosis                                                1
Hepatopancreatitis in prawns                                              1
Tropilaelaps spp.                                                         1
Bovine genital campylobacteriosis                                         1
Hendra viruses                                                            1
Avian influenza A viruses of high pathogenicity                           1
Turkey rhinotracheitis                                                    1
Duck virus hepatitis                                                      1
Necrotising hepatopancreatitis                                            1
Monkey pox                                                                1
New disease in rainbow trout                                              1
Yellow head virus genotype 1                                              1
Taura syndrome virus                                                      1
Theileria lestoquardi, Theileria luwenshuni and Theileria uilenbergi      1
Salmonellosis                                                             1
Acarapisosis of honey bees                                                1
Equine encephalosis virus                                                 1
Pigeon rotavirus                                                          1
Aeromonas hydrophila                                                      1
Streptococcus suis                                                        1
Botulism                                                                  1
Swine vesicular disease                                                   1
Caprine and ovine brucellosis                                             1
Ehrlichia canis                                                           1
Decapod iridescent Virus 1 infection                                      1
Infectious spleen and kidney necrosis                                     1
Mikrocytos mimicus n. sp.                                                 1
Macrobrachium rosenbergii nodavirus                                       1
Malignant catarrhal fever                                                 1
Abalone viral mortality                                                   1
Trichinellosis                                                            1
Postweaning Multisystemic Wasting Syndrome                                1
Taura syndrome                                                            1
Mycoplasma synoviae                                                       1
Name: count, dtype: int64

In [56]:
print("Unique diseases:", data["disease_name"].nunique())

Unique diseases: 193

In [60]:
# Count disease occurrences
disease_counts = data["disease_name"].value_counts()

# Keep diseases with at least 5 records
data_filtered = data[
    data["disease_name"].isin(
        disease_counts[disease_counts >= 10].index
    )
]

print("Original rows:", len(data))
print("Remaining rows:", len(data_filtered))
print("Remaining unique diseases:",
      data_filtered["disease_name"].nunique())

Original rows: 6332
Remaining rows: 5903
Remaining unique diseases: 78

In [66]:

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

print(data_filtered["disease_name"].value_counts())

disease_name
African swine fever virus                                               638
Influenza A viruses of high pathogenicity                               580
Highly pathogenic avian influenza                                       570
High pathogenicity avian influenza viruses                              531
Foot and mouth disease                                                  273
Anthrax                                                                 231
Highly pathogenic influenza A viruses                                   209
Foot and mouth disease virus                                            183
Low pathogenic avian influenza                                          178
Bluetongue virus                                                        153
Newcastle disease                                                       152
West Nile Fever                                                         147
Rabies virus                                                            146
Bluetongue                                                              131
African swine fever                                                     131
Sheep pox and goat pox                                                  121
Newcastle disease virus                                                  92
SARS-CoV-2 in animals                                                    89
Equine infectious anaemia                                                83
Lumpy skin disease virus                                                 69
Classical swine fever                                                    64
Rabies                                                                   60
Rabbit haemorrhagic disease                                              55
Bovine spongiform encephalopathy                                         51
Peste des petits ruminants virus                                         41
Peste des petits ruminants                                               39
Lumpy skin disease                                                       38
Brucellosis                                                              32
Influenza A virus                                                        32
Scrapie                                                                  31
Rift Valley fever                                                        28
Contagious equine metritis                                               26
New world screwworm                                                      26
Koi herpesvirus                                                          24
Koi herpesvirus disease                                                  23
Infectious haematopoietic necrosis virus                                 23
Rift Valley fever virus                                                  23
Infectious salmon anaemia virus                                          23
American foulbrood of honey bees                                         22
Porcine reproductive and respiratory syndrome                            21
European foulbrood of honey bees                                         19
Viral haemorrhagic septicaemia                                           18
African horse sickness                                                   18
Equine piroplasmosis                                                     18
Vesicular stomatitis                                                     17
Viral haemorrhagic septicaemia virus                                     17
Equine influenza virus                                                   17
Classical swine fever virus                                              16
Small hive beetle Inf.                                                   16
Fowl typhoid                                                             16
Equine encephalomyelitis                                                 16
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis     15
Myxomatosis                                                              15
Varroa spp.                                                              14
Aujeszky's disease virus                                                 14
Mycoplasma mycoides subsp. mycoides SC                                   14
Contagious bovine pleuropneumonia                                        14
Leishmaniosis                                                            14
Crayfish plague                                                          13
Equine influenza                                                         13
Epizootic hemorrhagic disease virus                                      13
White spot disease                                                       13
Melissococcus plutonius                                                  12
Venezuelan equine encephalomyelitis                                      12
Avian infectious laryngotracheitis                                       12
Ostreid herpesvirus-1                                                    12
Epizootic ulcerative syndrome                                            11
Tilapia lake virus disease                                               11
Caprine arthritis/encephalitis                                           11
African horse sickness virus                                             11
Aethina tumida                                                           11
Mycobacterium tuberculosis complex                                       11
Aujeszky's disease                                                       10
Aphanomyces invadans                                                     10
Perkinsus olseni                                                         10
Bonamia ostreae                                                          10
Glanders                                                                 10
Cochliomyia hominivorax                                                  10
Name: count, dtype: int64

In [68]:
disease_mapping = {

    "African swine fever virus": "African swine fever",

    "Influenza A viruses of high pathogenicity": "Highly pathogenic avian influenza",
    "High pathogenicity avian influenza viruses": "Highly pathogenic avian influenza",
    "Highly pathogenic influenza A viruses": "Highly pathogenic avian influenza",

    "Foot and mouth disease virus": "Foot and mouth disease",

    "Newcastle disease virus": "Newcastle disease",

    "Rabies virus": "Rabies",

    "Bluetongue virus": "Bluetongue",

    "Lumpy skin disease virus": "Lumpy skin disease",

    "Peste des petits ruminants virus": "Peste des petits ruminants",

    "Rift Valley fever virus": "Rift Valley fever",

    "Equine influenza virus": "Equine influenza",

    "Classical swine fever virus": "Classical swine fever",

    "Viral haemorrhagic septicaemia virus": "Viral haemorrhagic septicaemia",

    "African horse sickness virus": "African horse sickness",

    "Aujeszky's disease virus": "Aujeszky's disease",

    "Koi herpesvirus disease": "Koi herpesvirus",

    "Aethina tumida": "Small hive beetle infestation",
    "Small hive beetle Inf.": "Small hive beetle infestation"
}

data_filtered["disease_name"] = (
    data_filtered["disease_name"]
    .replace(disease_mapping)
)

C:\Users\nlnkr\AppData\Local\Temp\ipykernel_5732\351872621.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["disease_name"] = (

In [69]:
print(data_filtered["disease_name"].value_counts())
print("Unique diseases:", data_filtered["disease_name"].nunique())

disease_name
Highly pathogenic avian influenza                                       1890
African swine fever                                                      769
Foot and mouth disease                                                   456
Bluetongue                                                               284
Newcastle disease                                                        244
Anthrax                                                                  231
Rabies                                                                   206
Low pathogenic avian influenza                                           178
West Nile Fever                                                          147
Sheep pox and goat pox                                                   121
Lumpy skin disease                                                       107
SARS-CoV-2 in animals                                                     89
Equine infectious anaemia                                                 83
Classical swine fever                                                     80
Peste des petits ruminants                                                80
Rabbit haemorrhagic disease                                               55
Bovine spongiform encephalopathy                                          51
Rift Valley fever                                                         51
Koi herpesvirus                                                           47
Viral haemorrhagic septicaemia                                            35
Influenza A virus                                                         32
Brucellosis                                                               32
Scrapie                                                                   31
Equine influenza                                                          30
African horse sickness                                                    29
Small hive beetle infestation                                             27
New world screwworm                                                       26
Contagious equine metritis                                                26
Aujeszky's disease                                                        24
Infectious salmon anaemia virus                                           23
Infectious haematopoietic necrosis virus                                  23
American foulbrood of honey bees                                          22
Porcine reproductive and respiratory syndrome                             21
European foulbrood of honey bees                                          19
Equine piroplasmosis                                                      18
Vesicular stomatitis                                                      17
Fowl typhoid                                                              16
Equine encephalomyelitis                                                  16
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis      15
Myxomatosis                                                               15
Varroa spp.                                                               14
Mycoplasma mycoides subsp. mycoides SC                                    14
Contagious bovine pleuropneumonia                                         14
Leishmaniosis                                                             14
Crayfish plague                                                           13
Epizootic hemorrhagic disease virus                                       13
White spot disease                                                        13
Venezuelan equine encephalomyelitis                                       12
Ostreid herpesvirus-1                                                     12
Avian infectious laryngotracheitis                                        12
Melissococcus plutonius                                                   12
Caprine arthritis/encephalitis                                            11
Tilapia lake virus disease                                                11
Epizootic ulcerative syndrome                                             11
Mycobacterium tuberculosis complex                                        11
Glanders                                                                  10
Perkinsus olseni                                                          10
Bonamia ostreae                                                           10
Aphanomyces invadans                                                      10
Cochliomyia hominivorax                                                   10
Name: count, dtype: int64
Unique diseases: 60

In [70]:
counts = data_filtered["disease_name"].value_counts()

print("Minimum disease count:", counts.min())
print("Unique diseases:", len(counts))

Minimum disease count: 10
Unique diseases: 60

In [71]:
print(data_filtered["disease_name"].value_counts())

disease_name
Highly pathogenic avian influenza                                       1890
African swine fever                                                      769
Foot and mouth disease                                                   456
Bluetongue                                                               284
Newcastle disease                                                        244
Anthrax                                                                  231
Rabies                                                                   206
Low pathogenic avian influenza                                           178
West Nile Fever                                                          147
Sheep pox and goat pox                                                   121
Lumpy skin disease                                                       107
SARS-CoV-2 in animals                                                     89
Equine infectious anaemia                                                 83
Classical swine fever                                                     80
Peste des petits ruminants                                                80
Rabbit haemorrhagic disease                                               55
Bovine spongiform encephalopathy                                          51
Rift Valley fever                                                         51
Koi herpesvirus                                                           47
Viral haemorrhagic septicaemia                                            35
Influenza A virus                                                         32
Brucellosis                                                               32
Scrapie                                                                   31
Equine influenza                                                          30
African horse sickness                                                    29
Small hive beetle infestation                                             27
New world screwworm                                                       26
Contagious equine metritis                                                26
Aujeszky's disease                                                        24
Infectious salmon anaemia virus                                           23
Infectious haematopoietic necrosis virus                                  23
American foulbrood of honey bees                                          22
Porcine reproductive and respiratory syndrome                             21
European foulbrood of honey bees                                          19
Equine piroplasmosis                                                      18
Vesicular stomatitis                                                      17
Fowl typhoid                                                              16
Equine encephalomyelitis                                                  16
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis      15
Myxomatosis                                                               15
Varroa spp.                                                               14
Mycoplasma mycoides subsp. mycoides SC                                    14
Contagious bovine pleuropneumonia                                         14
Leishmaniosis                                                             14
Crayfish plague                                                           13
Epizootic hemorrhagic disease virus                                       13
White spot disease                                                        13
Venezuelan equine encephalomyelitis                                       12
Ostreid herpesvirus-1                                                     12
Avian infectious laryngotracheitis                                        12
Melissococcus plutonius                                                   12
Caprine arthritis/encephalitis                                            11
Tilapia lake virus disease                                                11
Epizootic ulcerative syndrome                                             11
Mycobacterium tuberculosis complex                                        11
Glanders                                                                  10
Perkinsus olseni                                                          10
Bonamia ostreae                                                           10
Aphanomyces invadans                                                      10
Cochliomyia hominivorax                                                   10
Name: count, dtype: int64

In [72]:
counts = data_filtered["disease_name"].value_counts()

print("Total rows:", len(data_filtered))
print("Unique diseases:", data_filtered["disease_name"].nunique())
print("Minimum samples:", counts.min())
print("Maximum samples:", counts.max())
print("Average samples:", counts.mean())

Total rows: 5903
Unique diseases: 60
Minimum samples: 10
Maximum samples: 1890
Average samples: 98.38333333333334

Train Test Split

In [79]:
from sklearn.model_selection import train_test_split

X = data_filtered.drop(columns=["disease_name"])
y = data_filtered["disease_name"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 4722
Testing rows: 1181

In [80]:
print("Train distribution:")
print(y_train.value_counts())

print("\nTest distribution:")
print(y_test.value_counts())

Train distribution:
disease_name
Highly pathogenic avian influenza                                       1512
African swine fever                                                      615
Foot and mouth disease                                                   365
Bluetongue                                                               227
Newcastle disease                                                        195
Anthrax                                                                  185
Rabies                                                                   165
Low pathogenic avian influenza                                           142
West Nile Fever                                                          117
Sheep pox and goat pox                                                    97
Lumpy skin disease                                                        85
SARS-CoV-2 in animals                                                     71
Equine infectious anaemia                                                 66
Classical swine fever                                                     64
Peste des petits ruminants                                                64
Rabbit haemorrhagic disease                                               44
Bovine spongiform encephalopathy                                          41
Rift Valley fever                                                         41
Koi herpesvirus                                                           37
Viral haemorrhagic septicaemia                                            28
Brucellosis                                                               26
Influenza A virus                                                         26
Scrapie                                                                   25
Equine influenza                                                          24
African horse sickness                                                    23
Small hive beetle infestation                                             22
New world screwworm                                                       21
Contagious equine metritis                                                21
Aujeszky's disease                                                        19
American foulbrood of honey bees                                          18
Infectious salmon anaemia virus                                           18
Infectious haematopoietic necrosis virus                                  18
Porcine reproductive and respiratory syndrome                             17
European foulbrood of honey bees                                          15
Vesicular stomatitis                                                      14
Equine piroplasmosis                                                      14
Equine encephalomyelitis                                                  13
Fowl typhoid                                                              13
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis      12
Myxomatosis                                                               12
Mycoplasma mycoides subsp. mycoides SC                                    11
Varroa spp.                                                               11
Contagious bovine pleuropneumonia                                         11
Leishmaniosis                                                             11
Melissococcus plutonius                                                   10
Avian infectious laryngotracheitis                                        10
Crayfish plague                                                           10
White spot disease                                                        10
Epizootic hemorrhagic disease virus                                       10
Ostreid herpesvirus-1                                                     10
Venezuelan equine encephalomyelitis                                       10
Caprine arthritis/encephalitis                                             9
Mycobacterium tuberculosis complex                                         9
Epizootic ulcerative syndrome                                              9
Tilapia lake virus disease                                                 9
Perkinsus olseni                                                           8
Aphanomyces invadans                                                       8
Cochliomyia hominivorax                                                    8
Glanders                                                                   8
Bonamia ostreae                                                            8
Name: count, dtype: int64

Test distribution:
disease_name
Highly pathogenic avian influenza                                       378
African swine fever                                                     154
Foot and mouth disease                                                   91
Bluetongue                                                               57
Newcastle disease                                                        49
Anthrax                                                                  46
Rabies                                                                   41
Low pathogenic avian influenza                                           36
West Nile Fever                                                          30
Sheep pox and goat pox                                                   24
Lumpy skin disease                                                       22
SARS-CoV-2 in animals                                                    18
Equine infectious anaemia                                                17
Classical swine fever                                                    16
Peste des petits ruminants                                               16
Rabbit haemorrhagic disease                                              11
Koi herpesvirus                                                          10
Bovine spongiform encephalopathy                                         10
Rift Valley fever                                                        10
Viral haemorrhagic septicaemia                                            7
Scrapie                                                                   6
Equine influenza                                                          6
African horse sickness                                                    6
Influenza A virus                                                         6
Brucellosis                                                               6
Small hive beetle infestation                                             5
Contagious equine metritis                                                5
Aujeszky's disease                                                        5
Infectious haematopoietic necrosis virus                                  5
Infectious salmon anaemia virus                                           5
New world screwworm                                                       5
American foulbrood of honey bees                                          4
Porcine reproductive and respiratory syndrome                             4
European foulbrood of honey bees                                          4
Equine piroplasmosis                                                      4
White spot disease                                                        3
Leishmaniosis                                                             3
Vesicular stomatitis                                                      3
Fowl typhoid                                                              3
Epizootic hemorrhagic disease virus                                       3
Equine encephalomyelitis                                                  3
Crayfish plague                                                           3
Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis      3
Contagious bovine pleuropneumonia                                         3
Mycoplasma mycoides subsp. mycoides SC                                    3
Myxomatosis                                                               3
Varroa spp.                                                               3
Mycobacterium tuberculosis complex                                        2
Melissococcus plutonius                                                   2
Ostreid herpesvirus-1                                                     2
Avian infectious laryngotracheitis                                        2
Venezuelan equine encephalomyelitis                                       2
Bonamia ostreae                                                           2
Epizootic ulcerative syndrome                                             2
Caprine arthritis/encephalitis                                            2
Cochliomyia hominivorax                                                   2
Aphanomyces invadans                                                      2
Tilapia lake virus disease                                                2
Glanders                                                                  2
Perkinsus olseni                                                          2
Name: count, dtype: int64

In [76]:
data_filtered["species_name"] = (
    data_filtered["species_name"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

C:\Users\nlnkr\AppData\Local\Temp\ipykernel_5732\2525053378.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["species_name"] = (

Encoding

In [85]:
X_train = X_train.copy()
X_test = X_test.copy()

In [86]:
species_counts = X_train["species_name"].value_counts()

common_species = species_counts[species_counts >= 10].index

X_train["species_name"] = X_train["species_name"].where(
    X_train["species_name"].isin(common_species),
    "Other"
)

X_test["species_name"] = X_test["species_name"].where(
    X_test["species_name"].isin(common_species),
    "Other"
)

Country — frequency encoding

In [87]:
country_freq = X_train["country_name"].value_counts(normalize=True)

X_train["country_freq"] = X_train["country_name"].map(country_freq)

X_test["country_freq"] = X_test["country_name"].map(country_freq)

X_test["country_freq"] = X_test["country_freq"].fillna(0)

In [88]:
X_train = X_train.drop(columns=["country_name"])
X_test = X_test.drop(columns=["country_name"])

Month — cyclical encoding

In [89]:
month_map = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

X_train["month_num"] = X_train["month"].map(month_map)
X_test["month_num"] = X_test["month"].map(month_map)

In [90]:
import numpy as np

X_train["month_sin"] = np.sin(2 * np.pi * X_train["month_num"] / 12)
X_train["month_cos"] = np.cos(2 * np.pi * X_train["month_num"] / 12)

X_test["month_sin"] = np.sin(2 * np.pi * X_test["month_num"] / 12)
X_test["month_cos"] = np.cos(2 * np.pi * X_test["month_num"] / 12)

In [91]:
X_train = X_train.drop(columns=["month", "month_num"])
X_test = X_test.drop(columns=["month", "month_num"])

susceptible — log transform

In [92]:
X_train["susceptible"] = np.log1p(X_train["susceptible"])
X_test["susceptible"] = np.log1p(X_test["susceptible"])

Define categorical and numerical columns

In [93]:
categorical_features = [
    "species_name",
    "causal_agent_type",
    "season",
    "epi_unit_type"
]

numeric_features = [
    "is_wild",
    "is_domestic",
    "is_aquatic",
    "latitude",
    "longitude",
    "susceptible",
    "country_freq",
    "month_sin",
    "month_cos"
]

In [94]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        ),
        (
            "numeric",
            StandardScaler(),
            numeric_features
        )
    ]
)

In [95]:
X_train_encoded = preprocessor.fit_transform(X_train)

X_test_encoded = preprocessor.transform(X_test)

In [96]:
print("Training shape:", X_train_encoded.shape)
print("Testing shape:", X_test_encoded.shape)

Training shape: (4722, 73)
Testing shape: (1181, 73)

Encode the disease target

In [97]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [98]:
for number, disease in enumerate(label_encoder.classes_):
    print(number, "=", disease)

0 = African horse sickness
1 = African swine fever
2 = American foulbrood of honey bees
3 = Anthrax
4 = Aphanomyces invadans
5 = Aujeszky's disease
6 = Avian infectious laryngotracheitis
7 = Bluetongue
8 = Bonamia ostreae
9 = Bovine spongiform encephalopathy
10 = Brucellosis
11 = Caprine arthritis/encephalitis
12 = Classical swine fever
13 = Cochliomyia hominivorax
14 = Contagious bovine pleuropneumonia
15 = Contagious equine metritis
16 = Crayfish plague
17 = Epizootic hemorrhagic disease virus
18 = Epizootic ulcerative syndrome
19 = Equine encephalomyelitis
20 = Equine infectious anaemia
21 = Equine influenza
22 = Equine piroplasmosis
23 = European foulbrood of honey bees
24 = Foot and mouth disease
25 = Fowl typhoid
26 = Glanders
27 = Highly pathogenic avian influenza
28 = Infectious bovine rhinotracheitis/infectious pustular vulvovaginitis
29 = Infectious haematopoietic necrosis virus
30 = Infectious salmon anaemia virus
31 = Influenza A virus
32 = Koi herpesvirus
33 = Leishmaniosis
34 = Low pathogenic avian influenza
35 = Lumpy skin disease
36 = Melissococcus plutonius
37 = Mycobacterium tuberculosis complex
38 = Mycoplasma mycoides subsp. mycoides SC
39 = Myxomatosis
40 = New world screwworm
41 = Newcastle disease
42 = Ostreid herpesvirus-1
43 = Perkinsus olseni
44 = Peste des petits ruminants
45 = Porcine reproductive and respiratory syndrome
46 = Rabbit haemorrhagic disease
47 = Rabies
48 = Rift Valley fever
49 = SARS-CoV-2 in animals
50 = Scrapie
51 = Sheep pox and goat pox
52 = Small hive beetle infestation
53 = Tilapia lake virus disease
54 = Varroa spp.
55 = Venezuelan equine encephalomyelitis
56 = Vesicular stomatitis
57 = Viral haemorrhagic septicaemia
58 = West Nile Fever
59 = White spot disease

Catboost

In [112]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from catboost import CatBoostClassifier
import numpy as np

In [113]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [126]:
accuracy_scores = []
macro_f1_scores = []
weighted_f1_scores = []

for fold, (train_index, val_index) in enumerate(
    skf.split(X_train_encoded, y_train_encoded), start=1
):

    print(f"\nTraining Fold {fold}/5")

    # Split the training data
    X_fold_train = X_train_encoded[train_index]
    X_fold_val = X_train_encoded[val_index]

    y_fold_train = y_train_encoded[train_index]
    y_fold_val = y_train_encoded[val_index]

    # Original model parameters + GPU
    fold_model = CatBoostClassifier(
        iterations=1000,
        depth=8,
        learning_rate=0.09,
        loss_function="MultiClass",
        eval_metric="TotalF1",
        auto_class_weights="Balanced",
        random_seed=42,

        # GPU configuration
        task_type="GPU",
        devices="0",

        verbose=False
    )

    # Train the model
    fold_model.fit(
        X_fold_train,
        y_fold_train
    )

    # Make predictions
    fold_predictions = fold_model.predict(
        X_fold_val
    ).flatten()

    # Calculate metrics
    accuracy = accuracy_score(
        y_fold_val,
        fold_predictions
    )

    macro_f1 = f1_score(
        y_fold_val,
        fold_predictions,
        average="macro",
        zero_division=0
    )

    weighted_f1 = f1_score(
        y_fold_val,
        fold_predictions,
        average="weighted",
        zero_division=0
    )

    # Store scores
    accuracy_scores.append(accuracy)
    macro_f1_scores.append(macro_f1)
    weighted_f1_scores.append(weighted_f1)

    print(f"Accuracy: {accuracy:.4f}")
    print(f"Macro F1: {macro_f1:.4f}")
    print(f"Weighted F1: {weighted_f1:.4f}")

Training Fold 1/5
Accuracy: 0.7704
Macro F1: 0.6042
Weighted F1: 0.7685

Training Fold 2/5
Accuracy: 0.7735
Macro F1: 0.6028
Weighted F1: 0.7677

Training Fold 3/5
Accuracy: 0.7860
Macro F1: 0.6200
Weighted F1: 0.7828

Training Fold 4/5
Accuracy: 0.7701
Macro F1: 0.5708
Weighted F1: 0.7675

Training Fold 5/5
Accuracy: 0.7828
Macro F1: 0.6130
Weighted F1: 0.7801

In [127]:
print("\n===== 5-Fold Cross-Validation Results =====")

print(
    f"Average Accuracy: "
    f"{np.mean(accuracy_scores):.4f}"
)

print(
    f"Average Macro F1: "
    f"{np.mean(macro_f1_scores):.4f}"
)

print(
    f"Average Weighted F1: "
    f"{np.mean(weighted_f1_scores):.4f}"
)

print("\nStandard Deviations:")

print(
    f"Accuracy Std: "
    f"{np.std(accuracy_scores):.4f}"
)

print(
    f"Macro F1 Std: "
    f"{np.std(macro_f1_scores):.4f}"
)

print(
    f"Weighted F1 Std: "
    f"{np.std(weighted_f1_scores):.4f}"
)

===== 5-Fold Cross-Validation Results =====
Average Accuracy: 0.7766
Average Macro F1: 0.6021
Average Weighted F1: 0.7734

Standard Deviations:
Accuracy Std: 0.0066
Macro F1 Std: 0.0169
Weighted F1 Std: 0.0067

In [128]:
import os
import joblib

os.makedirs("saved_models", exist_ok=True)

fold_model.save_model("saved_models/catboost_final.cbm")

joblib.dump(label_encoder, "saved_models/label_encoder.pkl")
joblib.dump({
    'preprocessor': preprocessor,
    'country_freq': country_freq,
    'common_species': common_species
}, "saved_models/preprocessing_assets.pkl")

print("Model, label encoder, and preprocessor assets saved successfully!")

Model and label encoder saved successfully!